[colors]
[colors.primary]
background = "#131328"
foreground = "#ECC0A0"

[colors.normal]
black   = "#131328"
red     = "#DE5F65"
green   = "#EC8B74"
yellow  = "#AF8878"
blue    = "#9498c2"
magenta = "#c69ec7"
cyan    = "#aab5cb"
white   = "#ECC0A0"

[colors.bright]
black   = "#7d7da4"
red     = "#f1a8ab"
green   = "#facdc2"
yellow  = "#d3bab0"
blue    = "#cdcfe4"
magenta = "#e9d7e9"
cyan    = "#e2e6ee"
white   = "#fcf3ec"

[colors.cursor]
text   = "#131328"
cursor = "#ECC0A0"

[colors.selection]
text       = "#fcf3ec"
background = "#3d3d64"
