accent = "#9498c2"
cursor = "#ECC0A0"
foreground = "#ECC0A0"
background = "#131328"
selection_foreground = "#fcf3ec"
selection_background = "#3d3d64"

color0 = "#131328"
color1 = "#DE5F65"
color2 = "#EC8B74"
color3 = "#AF8878"
color4 = "#9498c2"
color5 = "#c69ec7"
color6 = "#aab5cb"
color7 = "#ECC0A0"
color8 = "#7d7da4"
color9 = "#f1a8ab"
color10 = "#facdc2"
color11 = "#d3bab0"
color12 = "#cdcfe4"
color13 = "#e9d7e9"
color14 = "#e2e6ee"
color15 = "#fcf3ec"
